# Generated by Django 2.1.4 on 2018-12-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscricao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='curso',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='curso', to='curso.Curso'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='evento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='evento', to='evento.Evento'),
        ),
    ]
