# Generated by Django 2.1.4 on 2018-12-18 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Candidato')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('endereco', models.CharField(max_length=200, verbose_name='Endereço')),
                ('matricula', models.CharField(max_length=25, verbose_name='Matrícula')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('dta_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('curriculo', models.FileField(upload_to='documento_candidato', verbose_name='Curriculo')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Candidatos',
            },
        ),
    ]
