# Generated by Django 2.1.4 on 2018-12-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_auto_20181218_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
