# Generated by Django 2.1.4 on 2018-12-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0003_auto_20181218_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='celular',
            field=models.CharField(blank=True, max_length=15, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='dta_nascimento',
            field=models.DateField(blank=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='endereco',
            field=models.CharField(blank=True, max_length=200, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='matricula',
            field=models.CharField(blank=True, max_length=25, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='nome',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Candidato'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo'),
        ),
    ]
