# Generated by Django 2.1.4 on 2018-12-20 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0004_auto_20181219_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
