# Generated by Django 2.1.4 on 2018-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Curso')),
                ('qtd_vagas', models.IntegerField(verbose_name='Quantidade de Vagas')),
            ],
            options={
                'verbose_name_plural': 'Curso',
            },
        ),
    ]
