# Generated by Django 2.1.4 on 2018-12-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('dta_inicio', models.DateField(verbose_name='Data de Inicio do Evento')),
                ('dta_fim', models.DateField(verbose_name='Data Final do Evento')),
                ('situacao', models.CharField(choices=[('1', 'Aguardando Início das Inscrições'), ('2', 'Aberto'), ('3', 'Encerrado')], max_length=1, verbose_name='Situação')),
            ],
            options={
                'verbose_name_plural': 'Eventos',
            },
        ),
    ]
